### ISSUE TITLE
SeqViews.empty()

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#22]
Is declared internal!

**Comment by Glavo** [comment]
Why do you need it instead of `Seq.of()`?

**Comment by Glavo** [comment]
I think we should use `SeqLike` more widely than `SeqView`, and call the `view()` to convert when necessary (for `SeqView`, this method only returns itself)

**Comment by ice1000** [comment]
> Why do you need it instead of `Seq.of()`?

`Seq.of().view()` doesn't interact nicely with type-inference

**Comment by ice1000** [comment]
> I think we should use `SeqLike` more widely than `SeqView`, and call the `view()` to convert when necessary (for `SeqView`, this method only returns itself)

Ok, wise suggestion
