### ISSUE TITLE
`ImmSeq::from(java.util.List)`

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#31]
So we can know the list size already to avoid realloc

**Comment by Glavo** [comment]
This is the current default behavior, see [ImmutableVector.java#L157](https://github.com/Glavo/kala-common/blob/53e1f17884ee839d482559b6b6fa1e27fd8c9eec/kala-collection/src/main/java/org/glavo/kala/collection/immutable/ImmutableVector.java#L157).
