### ISSUE TITLE
删除不可变集合的 `map`/`filter` 等操作“？

### ISSUE THREAD

**Issue by Glavo** [Glavo/kala-common#44]
目前，kala 的不可变集合提供了 `map`/`filter` 等一系列操作，这些操作都是从 Scala 的集合中继承而来的。而可变集合并没有提供。

这样做的原意是：不可变集合相对来说更依赖这些操作，所以实现它们更便捷。而可变集合应该重点在可变的处理上，提供这些操作很容易造成迷惑。

特别是，按照 Scala 集合的惯例，这些操作返回的都是和原集合相同的集合，我厌恶没有明确标注的方法返回可变的集合，因为这非常迷惑（因此目前没有提供 `toDynamicSeq` 等系列操作，而在未来可能会用 `copyToDynamicSeq` 这样明确的名称提供类似的功能）。

同时，我提供了一套 `View` 机制，任何集合可以通过 `.view()` 生成一个 `View`，`View` 与不可变集合一样提供了这些操作。
可变集合通过 `View` 也可以轻松地使用这些操作，更加明确意图。

---

但是，在长时间的投入生产使用中后，我发现这存在一些很严重的问题：

### 容易被链式调用

对于不可变集合来说，链式调用这些操作是很自然的：

```java
var res = seq.map(...).filter(...).flatMap(...)
```

这样的用法不管在 Scala、Kotlin 还是 Kala 中都很常见，但这是**不推荐**的，因为这会产生很多不必要的中间集合。

建议的做法是使用 `View` 机制：

```java
var res = seq.view().map(...).filter(...).flatMap(...).toImmutableSeq()
```

这将惰性地生成最后的序列，而不需要每个操作后产生一个中间结果。

### 极高的维护成本/低下的可扩展性

各个 `View` 和不可变集合中都存在这样的一套方法，这套方法继承了 Scala 的惯例：每个集合类型中实现的操作返回的都是该类型的集合。

但是，Java 中不存在自身类型（Self-Type）和高阶类型（Higher-Kinded Type） 。为了保持这套设计，必须在每个集合中覆盖每个方法以保证签名的正确性。

Kala 使用了一套繁琐复杂的设计来保证实现的正确性。每次修改/添加方法，都需要把它们全部修改：

* `FullCollection(Seq/Set)Like`：所有的 `View` 与不可变集合的父类，定义了这类操作的基本签名。
    
    ```java
    public interface FullCollectionLike<E> extends CollectionLike<E> {
        <U> FullCollectionLike<U> map(Function<? super E, ? extends U> mapper);
    }
    ```
  
* `FullCollection(Seq/Set)LikeOps`：由于 Java 缺乏高阶类型，需要每个集合的实现类实现它，使 Java 编译器能够识别并强制保证每个集合类重写这些方法的签名。

    ```java
    public interface FullCollectionLikeOps<E, CC extends CollectionLike<?>, COLL extends CollectionLike<E>>
        extends CollectionLike<E> {        
        <U> CC map(Function<? super E, ? extends U> mapper);
    }
    ```

* `ImmutableCollection(Seq/Set)`, `(Seq/Set)View`：表示不可变集合和 `View` 的接口，它们中的每个都应该通过覆盖重写一次签名。

    ```java
    public interface ImmutableCollection<E> extends Collection<E>, FullCollectionLike<E> {
        default <U> ImmutableCollection<U> map(Function<? super E, ? extends U> mapper) {
            return AbstractImmutableCollection.map(this, mapper, this.<U>iterableFactory());
        }
    }
    ```

* `AbstractImmutableCollection(Seq/Set)`：以静态方法形式提供接口方法的默认实现（规避一些泛型问题），
   并提供一套便于在子类中使用默认实现的便捷方法。

    ```java
    public abstract class AbstractImmutableCollection<@Covariant E>
        extends AbstractCollection<E> implements ImmutableCollection<E> {
        static <E, U, T, Builder> T map(
            ImmutableCollection<? extends E> collection,
            Function<? super E, ? extends U> mapper,
            CollectionFactory<? super U, Builder, ? extends T> factory
        ) {
            // ...
        }
  
        protected final <U, To extends ImmutableCollection<U>> To mapImplFunction<? super E, ? extends U> mapper) {
            return (To) AbstractImmutableCollection.map(this, mapper, iterableFactory());
        }    
    }
    ```
  
* 每个 `public` 的集合实现类：都需要重写全部方法以覆盖签名，即使想使用默认实现。

这对于维护来说难度过大，而且实现的并不漂亮，但为了迁就 Java 的类型系统，很难避免复杂的设计。

同时，这对于扩展性来说堪称地狱。用户如果实现了自己的不可变集合类型，在每次 Kala 加入新的操作后都不得修改自己的代码来覆盖它们，这是很恶劣的问题。

---

因为上面所述的原因，我考虑将这些操作也从不可变集合中删除，而用户依然可以使用 `View` 来实现这些操作。

如果删除这些操作，我也能把更多精力集中在优化 `View` 上。

**Comment by ice1000** [comment]
支持！！！！！！！！！！！！！！！！！！！！1

**Comment by Glavo** [comment]
See #48
