### ISSUE TITLE
使用新的架构重构 kala-common

### ISSUE THREAD

**Issue by Glavo** [Glavo/kala-common#48]
## 问题

经过一段时间的维护和生产使用后，kala 的架构暴露出了这样的问题：

1. 设计时将 `kala.base` 和 `kala.collection` 模块完全分离，缩减了 `kala.base` 大小，使其能单独使用，
   但也让 `kala.base` 模块中无法接受或返回 `kala.collection` 中的集合。
   同时，因为 JPMS 要求一个包只能对应一个模块，`kala.base` 无法声明 `kala.collection` 包下的类，
   不得不将一些集合的基础设施放在 `kala.collection.base` 包下。

2. kala 包含一套 `Factory` 设施，提供了对集合工厂方法的抽象。但是，为了便于使用，`kala.collection` 依然需要在每个类中声明一系列静态的工厂方法。
   由于 Java 无法对一个类中静态方法进行约束，kala 只能靠文档描述的弱约束来挨个实现静态工厂，也没办法为它们提供默认实现，造成了大量重复工作，每次修改都可能因为遗漏而产生 bug。
   而且因为集合同时需要提供 `Factory`，kala 通常会为每个集合类型声明一个 `Factory`，覆盖 `Factory` 的方法并委托至静态的工厂方法中。
   如果想要复用 `Factory` 中的默认实现来实现工厂方法，又需要让部分工厂方法的实现委托至 `Factory`。这样的双向依赖造成了很多混乱，
   也很容易因为疏忽产生无限递归。

3. 在 #44 中已经详细描述过的问题：为了维护从 Scala 中继承而来的惯例，`kala.collection` 中的每个集合实现都要覆盖大量方法的签名，
   并需要一套复杂的体系来保证覆盖的正确性（详见 #44）。这使得 `kala.collection` 不可变集合维护成本极高，而扩展性非常低下。

## 新的架构

在此之前，我提出了 #44，试图解决第三个问题。但这个方案遗漏了很多事情，所以此次尝试完全失败。

在这里，我提出一个新的架构，希望能够彻底解决以上问题：

1. 将 `Seq`/`MutableSeq`/`ImmutableSeq` 这一类集合接口，
   以及 `kala.collection`/`kala.collection.mutable`/`kala.collection.immutable` 这三个包移动至 `kala.base` 模块中。
   删除 `MapBase`，因为它是 `kala.base` 模块无法访问 `Map` 而做的妥协，现在不再被需要。

2. 将集合的具体实现类（例如：`ImmutableVector`）移动至 `kala.collection.impl`/`kala.collection.mutable.impl`/`kala.collection.immutable.impl` 包中。

3. 重新设计 `Factory`，使其泛型化。

4. 删除集合的具体实现类中的静态工厂方法，仅暴露对应的 `Factory` 对象。

5. 不可变集合不再覆盖超类中 `map`、`filter` 等方法的返回签名，仅返回 `ImmutableSeq` 等抽象接口类型。
   删除 `FullCollectionLike`、`FullCollectionOps` 等为了保证返回签名而提供的约束接口。

6. 提供 `kala.modules.KalaCollectionModule` 接口，可以通过它的方法获取各个集合实现类的 `Factory` 对象。
   `kala.collection` 模块提供 `KalaCollectionModule` 的实现，运行时在 `kala.base` 模块中通过反射动态加载。
   在加载失败时提供一个默认实现，默认实现中可以获取到一系列特殊无效 `Factory`，
   这些 `Factory` 每个操作都会抛出 `UnsupportedOperationException` 或者 `IllegalStateException`，提示用户没有找到可用的实现。

7. 提供类似 `ImmutableSeqs` 的静态类，存放其对应类的实现的 `Factory`。

8. 提供 `kala.annotations.DependsOn` 接口，声明某个 API 函数依赖于另一个模块。

## 问题

1. 现有的 `Factory` 是对应一个元素类型的，需要重新设计，使其支持泛型化。

2. 每个集合实现类想拥有自己的独特工厂方法（例如，`MutableArray` 需要 `create(int)` 方法）需要一个独特的 `Factory` 类型，
   可能导致 `kala.base` 模块不必要的膨胀，让 `kala.base` 和 `kala.collection` 分离的价值下降。

3. 使用接口类型掩盖具体的实现类型后，JVM 更难对方法进行去虚化，可能更容易产生虚调用。

4. 工厂名称的选择（像 `DynamicSeqs.Array` 这样的名称足够合理吗？）

5. 与 `Stream::collect` 的兼容性（泛型化的 `Factory` 可能无法直接传入其中）

---

这是一个意见收集 Issue，希望得到用户的建议进一步完善。

**Comment by Glavo** [comment]
@ice1000 @imkiva

**Comment by ice1000** [comment]
用反射动态加载会不会对 graalvm 打包 native image 造成困难？

**Comment by ice1000** [comment]
> 当前 kala 的集合框架已经很难维护，重构后

是不是没写完

**Comment by Glavo** [comment]
> 用反射动态加载会不会对 graalvm 打包 native image 造成困难？

这个我专门调查过了。根据 [Reflection Use in Native Images#Automatic Detection](https://www.graalvm.org/reference-manual/native-image/Reflection/) 一节中的说法：

> If the arguments to these calls can be reduced to a constant, Native Image tries to resolve the target elements. If the target elements can be resolved, the calls are removed and instead the target elements are embedded in the code. If the target elements cannot be resolved, e.g., a class is not on the classpath or it does not declare a field/method/constructor, then the calls are replaced with a snippet that throws the appropriate exception at run time. The benefits are twofold. First, at run time there are no calls to the Reflection API. Second, GraalVM can employ constant folding and optimize the code further.

只要保证在内联后 `Class.forName` 接受的是常量字符串，native-image 会消除反射调用。实现的时候注意一点应该就可以了。

**Comment by ice1000** [comment]
> 1. 现有的 `Factory` 是对应一个元素类型的，需要重新设计，使其支持泛型化。

什么是「对应一个元素类型」？

> 2. 每个集合实现类想拥有自己的独特工厂方法（例如，`MutableArray` 需要 `create(int)` 方法）需要一个独特的 `Factory` 类型，
>    可能导致 `kala.base` 模块不必要的膨胀，让 `kala.base` 和 `kala.collection` 分离的价值下降。

大概会有多少个 factory？

> 3. 使用接口类型掩盖具体的实现类型后，JVM 更难对方法进行去虚化，可能更容易产生虚调用。

我记得现在也有很多虚函数和 lambda，我觉得不会 make it worse

> 4. 工厂名称的选择（像 `DynamicSeqs.Array` 这样的名称足够合理吗？）

我觉得很不错啊，我没李姐错的话实现是自动查找的吧？

> 5. 与 `Stream::collect` 的兼容性（泛型化的 `Factory` 可能无法直接传入其中）

可以提供一个擦除函数 `.steamApi()`

**Comment by ice1000** [comment]
我是想说 `.streamApi`……打错了。

**Comment by Glavo** [comment]
> > 1. 现有的 `Factory` 是对应一个元素类型的，需要重新设计，使其支持泛型化。
> 
> 什么是「对应一个元素类型」？

目前 `CollectionFactory` 大概是这样的：

```java
public interface CollectionFactory<E, Builder, R> 
    extends Factory<Builder, R>, Collector<E, Builder, R> {
    R from(Iterable<? extends E> values);
}
```

可以注意到这个泛型参数 E 是指定在 `CollectionFactory` 里的，也就是每个 `CollectionFactory` 已经定好对应的集合类型了。

这个 `CollectionFactory` 属于 Java 的 `Collector` 的进阶版，但是满足不了新的设计的需求，新的设计想要的是大概这样一套：

```java
public interace ImmutableSeqFactory {
    <E> ImmutableSeq<E> from(Iterable<? extends E> values);
}
```

这样的话，很多东西就都需要重新设计了。原本的 `Factory` 看起来依然有存在的必要，但是估计需要改个名。

> > 1. 每个集合实现类想拥有自己的独特工厂方法（例如，`MutableArray` 需要 `create(int)` 方法）需要一个独特的 `Factory` 类型，
> >    可能导致 `kala.base` 模块不必要的膨胀，让 `kala.base` 和 `kala.collection` 分离的价值下降。
> 
> 大概会有多少个 factory？

为了保持形式规整，可能每个实现类都要对应一个接口。

膨胀一点倒无所谓，但我担心这会让拆分模块的意义变小甚至变成负收益。

本身就要移动大量接口和部分实现类（譬如 `View` 的那套）到 `kala.base` 里，如果还会造成额外的体积膨胀的话，也许合并模块是更好的选择。

> > 1. 使用接口类型掩盖具体的实现类型后，JVM 更难对方法进行去虚化，可能更容易产生虚调用。
> 
> 我记得现在也有很多虚函数和 lambda，我觉得不会 make it worse

现在虚函数实际没那么多，因为已经尽量避免了，希望影响别太大。

> > 1. 工厂名称的选择（像 `DynamicSeqs.Array` 这样的名称足够合理吗？）
> 
> 我觉得很不错啊，我没李姐错的话实现是自动查找的吧？

大概就是改成这个样子：

```java
public class DynamicSeqs {
    public static final DynamicSeqFactory Array = ...;
}
```

```java
DynamicSeq seq = DynamicSeqs.Array.of(0, 1, 2);
```

但我还是感觉有点丑……我再想想怎么放。

> > 1. 与 `Stream::collect` 的兼容性（泛型化的 `Factory` 可能无法直接传入其中）
> 
> 可以提供一个擦除函数 `.steamApi()`

`.collector()` 就行。

**Comment by ice1000** [comment]
0. 我觉得你应该合并模块，过小的模块抽象出来有过度工程的嫌疑
1. 我觉得你提供一个不指定实现的工厂方法比如 DynamicSeq.of 就没问题，具体的实现长点真的太没关系了。纠结这点代码长度不如去把 ImmutableSeq/DynamicSeq 重命名成 ImmSeq/DynSeq

**Comment by Glavo** [comment]
> 1. 我觉得你应该合并模块，过小的模块抽象出来有过度工程的嫌疑
> 2. 我觉得你提供一个不指定实现的工厂方法比如 DynamicSeq.of 就没问题，具体的实现长点真的太没关系了。纠结这点代码长度不如去把 ImmutableSeq/DynamicSeq 重命名成 ImmSeq/DynSeq

不是长度问题啊，我从头到尾就根本没说过长度问题的事啊，因为长度本来就不是问题。

现在的问题是：
* 每个集合类都要复制粘贴出来至少 15 个静态工厂方法，SortedMap/SortedSet 更是要 30+ 个静态工厂方法，大量复制粘贴而且又难测试，而且想利用 `Factory` 中的默认实现的话还需要造成双向依赖，一个不注意就是无限递归。
* 每添加一个生成新集合的方法（就像 `mapChecked`），都要在超过十个类里添加签名各异的各种实现，而且随着实现类的增加，要改的东西也在稳步增加。

**Comment by ice1000** [comment]
现在不也没解决这个问题吗……

**Comment by Glavo** [comment]
> 现在不也没解决这个问题吗……

这个方案不就是解决了这些问题吗？

**Comment by ice1000** [comment]
> > 现在不也没解决这个问题吗……
> 
> 这个方案不就是解决了这些问题吗？

那是你没看懂我之前说的。我就是随口提了一下命名的问题，我觉得 `DynamicSeqs.Array.of` 这种使用具体实现的工厂函数并不长（但是原因也有「需求小」在里面），但是可能需要 `DynamicSeq.of` 这样的不指定实现的工厂函数来解决大部分情况下的需求（如果代码里处处都是 Kala 里的 boilerplate，也不好）。

**Comment by imkiva** [comment]
> 1. 现有的 `Factory` 是对应一个元素类型的，需要重新设计，使其支持泛型化。

使用新架构后，由于「原本的 Factory 看起来依然有存在的必要」，是出于什么考虑需要保留这些原有的 Factory 呢？）一个猜想，不一定对：是需要在 `Stream::collect` 中作为参数吗？）

> 2. 每个集合实现类想拥有自己的独特工厂方法（例如，`MutableArray` 需要 `create(int)` 方法）需要一个独特的 `Factory` 类型，
>    可能导致 `kala.base` 模块不必要的膨胀，让 `kala.base` 和 `kala.collection` 分离的价值下降。

建议合并 `kala.base` 和 `kala.collection`。或者将 `kala.base` 中的 collection 的抽象或实现全部移动到  `kala.collection` 中，在 `kala.base` 中仅保留 controls, function, value 之类的功能，这样 `kala.base` 仍然可以单独使用，而且这样 `kala.collection` 和名字更加相符（只简单看了一下 base 的目录结构，如果说的不对请忽略 QwQ）

> 3. 使用接口类型掩盖具体的实现类型后，JVM 更难对方法进行去虚化，可能更容易产生虚调用。

和 @ice1000 的观点相同

> 4. 工厂名称的选择（像 `DynamicSeqs.Array` 这样的名称足够合理吗？）

我觉得这样比之前的 `LinkedBuffer` 和 `ArrayBuffer` 之类的更加合理（主要是好看，公共前缀比公共后缀更容易辨认）。但是还是希望能直接使用 `DynamicSeqs.of()` 一类的方法 （方便起见可以直接委托至 `DynamicSeqs.Array`，因为使用这种 API 的时候用户并不关心内部的表示）。

> 5. 与 `Stream::collect` 的兼容性（泛型化的 `Factory` 可能无法直接传入其中）

emmm 暂时也不知道怎么修改，~~我觉得可以直接把 `Stream` 扬了~~

**Comment by Glavo** [comment]
> > > 现在不也没解决这个问题吗……
> > 
> > 
> > 这个方案不就是解决了这些问题吗？
> 
> 那是你没看懂我之前说的。我就是随口提了一下命名的问题，我觉得 `DynamicSeqs.Array.of` 这种使用具体实现的工厂函数并不长（但是原因也有「需求小」在里面），但是可能需要 `DynamicSeq.of` 这样的不指定实现的工厂函数来解决大部分情况下的需求（如果代码里处处都是 Kala 里的 boilerplate，也不好）。

接口中的静态工厂会保留的，委托到 `DynamicSeqs.Default` 之类的东西上。

**Comment by ice1000** [comment]
我已经等不及了，快端上来罢

**Comment by Glavo** [comment]
感觉完全这样重构不太现实，准备用一个更容易实现的简化办法：不再保证 `map`/`filter` 等一系列方法的返回值类型，都只返回 `Seq` 等接口。
