### ISSUE TITLE
`IntStream.range`?

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#51]
想要 🥺

**Comment by Glavo** [comment]
喵？具体是什么？

**Comment by ice1000** [comment]
就是整个类似的东西给比如 SeqView

**Comment by Glavo** [comment]
> 就是整个类似的东西给比如 SeqView

感觉往泛型集合里塞不好，准备等着集合特化后再说。

**Comment by Glavo** [comment]
0.33.0 发了，你可以暂时先这样：

```java
jshell> import kala.range.primitive.*; import kala.collection.immutable.*;

jshell> ImmutableSeq.from(IntRange.closed(10, 20).asTraversable())
$3 ==> ImmutableVector[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```

**Comment by ice1000** [comment]
> 0.33.0 发了，你可以暂时先这样：
> 
> ```java
> jshell> import kala.range.primitive.*; import kala.collection.immutable.*;
> 
> jshell> ImmutableSeq.from(IntRange.closed(10, 20).asTraversable())
> $3 ==> ImmutableVector[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
> ```

这么强
