### ISSUE TITLE
Publish to maven central?

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#52]
🤔

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/146170419-5d233759-6be9-4749-ab89-a9049db7a6c1.png)

**Comment by ice1000** [comment]
😨

**Comment by Glavo** [comment]
暂时不是很想……JitPack 适合敏捷发版，Maven Central 就麻烦一些……

如果很必要的话那我发上去？

**Comment by ice1000** [comment]
> 暂时不是很想……JitPack 适合敏捷发版，Maven Central 就麻烦一些……
> 
> 如果很必要的话那我发上去？

我觉得没有任何坏处，maven central 操作不也挺快的吗 🤔 而且 jitpack 不是有包名限制

**Comment by ice1000** [comment]
你 readme 里写的也和 jitpack 上写的不一样…不太懂🤔
