### ISSUE TITLE
不要求元素 Comparable 的 ImmutableSet 实现?

### ISSUE THREAD

**Issue by PhotonQuantum** [Glavo/kala-common#54]
现在 ImmutableSet 的实现只有 ImmutableCompactSet，也就是说现有的所有 ImmutableSet 都要求元素 Comparable。

有没有计划实现 ImmutableHashSet 或者另外某种非 Sorted 的 ImmutableSet?

**Comment by Glavo** [comment]
合理的 `ImmutableHashSet` 实现比较复杂，所以暂时还没做，我有空看着弄一下吧。

**Comment by Glavo** [comment]
考虑用 Compressed Hash-Array Mapped Prefix-tree 实现它。
