### ISSUE TITLE
Need a reliable way to create a list-backed stack

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#70]
If you want an instance of `MutableStack` created by `MutableList.create().asMutableStack()`, you will have to specify the type explicitly. Need something like `MutableStack.from(MutableList.create())`.

**Comment by Glavo** [comment]
When is this usage necessary? Why not use `MutableStack.create()` instead?

**Comment by ice1000** [comment]
> When is this usage necessary? Why not use `MutableStack.create()` instead?

I will not use a linked list in Java unless someone pay me explicitly to use it. It's cache unfriendly and takes more memory. Arrays are very efficient compared to linked lists even if you are inserting to the beginning. Not to even mention that we're inserting at ends for stacks
