### ISSUE TITLE
A method for testing two eithers

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#71]
So like I want a method that:

+ takes `x : Either<A, B>` and `y : Either<C, D>`
+ takes `f : (A, C) -> R`, `g : (B, D) -> R` and `u : R`
+ if `x is Left(a), y is Right(c)`, returns `f(a, c)`
+ similarly for `g`
+ return `u` by default

**Comment by HoshinoTented** [comment]
🤔 `y is Right(c) : C` ? But `y` has type `Either<C, D>`

**Comment by ice1000** [comment]
> 🤔 `y is Right(c) : C` ? But `y` has type `Either<C, D>`

Should be left, my bad
